[build]
  command = "npm run export"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]
